/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dashj */

#ifndef _Included_Dashj
#define _Included_Dashj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dashj
 * Method:    GetAddressByPrivateKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Dashj_GetAddressByPrivateKey
        (JNIEnv *, jobject, jstring);

/*
 * Class:     Dashj
 * Method:    SignTranscation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Dashj_SignTranscation
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
